# Generated by Django 5.1.4 on 2025-01-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_otpverification_firstname_otpverification_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='HazardCategory',
            field=models.CharField(blank=True, choices=[('traffic', 'Traffic'), ('infrastructure', 'Infrastructure'), ('environment', 'Environment'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
